language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Gbx8jbRXgkzps0e370lbVbSa0OGFy1nLPerYh+2AWmf4ahsh6q00RIyKEX6WM00Fum46uZGOQ8vYcEBEoQkYvUXWuk+ATG1W8a2ylSE0oGALHnYANv8SLAb+jar5NOvpOeQ8qhYXkeiLrHHsHRV28ppEDwnJZhrF2fi70nwDbNVTMP9oPJTvDSG2xo9joS3HtR8pl6M+zd+6ivdEUndE/uWc8KKdORZDFiH2Gk7PxHYWKMlP9rC+ImsGFRmtZiYtFDUbqiPfYvUBN0VaMWmZ5F0hd4XayijwjwNHN+54waWShZSyQ84RAfUg/bZO52tOzYGgEyAI7o6J2Y9JVYbfPGuKuFWlPZEjr0YABHeXRIjot2lI8gptVzG5KMHnGzDbymVgABS85rCblf96c9yHpoqL9Wiftua+irr90gJdJ140Dd4p2rVJzmuZ0FQJIehrKXaK+XDFsaxksI6hb65Lca+VZdHzIdZ8LXo0PHZRfRvPnJNe7C8jX8MplTnee0pJV6g23wlJBsCONuD3Ub3iNGgJt7Z84kLyfxL5nFKslBf2cyhA1Z2kjLiWmlQnT202h0xcNdbIsh9nNW2zUbcqD1HM/lyYNwmu2dVcNNJdK7LR+hq5hFlI7IbNNa/TWF0AgXUBMy0tIWFAHbcFWeZrcmOOnQ0cMHfoNVW2o8Y6o28="
env:
  secure: "CPHiZa6VFpl6JiyNKkIeFj9FqGpiSZBTmAAqmjG9/KKBRN3W10Ps+BOtFaa+A7WotUIv4Tw6eCEYN5BYbKEICWG35WglruYJNHr3875IdKMtPZ908niEHRraYkAr20VcPVp+SlwpHlB6DHSy67Y8IVg8PEdz/TwW0YB3AKUjWtZbtnYiK8b0T0wt4wiD1fbQiBLlYEIyGIrT4A+cgBBvPRF/MO657G5PhFueiQ7cyop5zAFXcmQMMDowW/zH7zK3XXPM2tTZVhHFpU5JniByjUoLg5COqlOaViSDbkrWa3z/ksVmhB/EYnVtzSIcOtyiZswi4GUOsFuYK0oEJpNxTfhQBzxytOLIQdEXNBghsc8MggKP22W3h3wQZ1Y2YY7LZjbTTZabqgIWGDtGbF42yw8p59Wv0bNWGYqT8VLwxuj6uqveEGK7GeiV8yb0hy8P/VvUlTHHCAEJ76X0KP469RNkL//l2T+gug3AQUnEqUW9jGQDP6qWNYQRAGQrmRxtB1Y0mUa2VfBMpIhE8UuDO8knOyW0IxacajRY9stZnzAEWGnRj4bZxpAwDt1LeG2ZD8JHwoWLHDlMufDaDaAc45ntx7HJaEtLcSMuxOSqEzB1sieatWU8b33zLnAenaZVRKvq3pYusK1lretyJiqFqI38wmMgUgkkdLi8pGHQfa8="
env:
  secure: "MlBTfJ6rwskOPnHrDq/DxIY6ZWz7fDA7G97kUUe1vnUojFcjDW5yTmsY/8S8kWjOgTLwvqnBOHwJAES5vHlploQQiunhjzeEQZWnangExj5KH87pOvDIECFeB5eXZ2Il4WTSw2vS7MGiJ06DnUJpEyigrtbTjntbkTGvmuHYpm3S9jiGRTDRf6mgJOtw2nY9YyoNMOQbV8yWyecvRMYuvqTn7XINEW5HaCt70poxJjPHSgpM3IAosxI9EQYDV6w0755icwe5NIyu0cP4htmwbPLcv0V20elMVwTSCBHoSKRyJEY/6tvVNGuPe+sbds1+mlPnIXTGwZ9Ri5KE+jT9B+ogIvYUaXLamUQMDJfXEd5FHmT5Beu+sfeLDdca5jBN+kCld9lnT+tFgmwS67ko/RLtibEGK8uUXvElmMc3TofmBqR3Ycs9mo3pVOQzgqLCaMUXxtwGe35tIxUffBFYqn9Z72C4mc5Juf7HTgjsfRrSc3LSan2mi+UyQCmCT60/CShVqWgFWQjVSj5HBot4bzHBmXCOq6/2no8yow6DxKxVsmSuNim2LlYSqpGvtjSLdAaQq0c4EYgdTj5zQnfI6fB70rQlzfO1FCI73Qg5e2dpikD4OBPtLcKJq8Z18n1fyzkiH1H24KB7ZZYhuoybeJQiL+XLr4DkODFmAciJ07A="
